# Generated by Django 2.1.1 on 2018-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_times_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='published',
            new_name='is_live',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('i', 'In Progress'), ('r', 'In Review'), ('p', 'Published')], default='i', max_length=1),
        ),
    ]
